import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { ethers } from "ethers";
import { useAccount } from "wagmi";

export default function Home() {
  const { address, isConnected } = useAccount();
  return (
    <div className={styles.main} style={{ backgroundColor: "white" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ConnectButton></ConnectButton>
        {isConnected && <p>you are connected</p>}
      </div>
    </div>
  );
}
